/**
 * Media manifest.
 *
 * All assets resolve under MEDIA_BASE ("/media" by default, prefixed with
 * NEXT_PUBLIC_BASE_PATH on sub-path hosts such as GitHub Pages). Point
 * NEXT_PUBLIC_MEDIA_BASE at a CDN that mirrors the same paths to swap the
 * generated placeholders for real footage without touching components.
 *
 * Generated by `npm run media` (scripts/generate-media.mjs).
 */

import type { MediaImage } from "./types";

const BASE_PATH = (process.env.NEXT_PUBLIC_BASE_PATH ?? "").replace(/\/$/, "");

export const MEDIA_BASE = process.env.NEXT_PUBLIC_MEDIA_BASE ?? `${BASE_PATH}/media`;

export const media = (path: string) => `${MEDIA_BASE}/${path.replace(/^\/+/, "")}`;

export const HERO_VIDEO = {
  webm: media("hero/hero.webm"),
  mp4: media("hero/hero.mp4"), // optional — ship if you have an H.264 encode
  poster: media("hero/poster.jpg"),
  posterBlur: media("hero/poster-blur.jpg"),
  width: 1920,
  height: 1080,
};

export const image = (
  path: string,
  alt: string,
  width = 2000,
  height = 1250,
): MediaImage => ({
  src: media(path),
  blur: media(path.replace(/\.(jpg|jpeg|png|webp)$/i, "-blur.$1")),
  alt,
  width,
  height,
});

export const portrait = (n: number) => media(`portraits/p${String(n).padStart(2, "0")}.jpg`);
export const curatorPortrait = (n: number) => media(`curators/c${String(n).padStart(2, "0")}.jpg`);
